# The language in this case has no bearing - we are going to be making use of conda for a
# python distribution for the scientific python stack.
language: generic

sudo: false

env:
    global:
       - CONDA_INSTALL_LOCN="${HOME}/conda"

    matrix:
        - PYTHON_STRING=py27
        - PYTHON_STRING=py34
        - PYTHON_STRING=py35

os:
  - osx
  - linux
  
install:
    - mkdir -p ${HOME}/cache/pkgs
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CONDA_ARCH_TAG="MacOSX" ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CONDA_ARCH_TAG="Linux" ; fi
    - export CONSTRUCTION="anvil-0.1.1-${PYTHON_STRING}-${CONDA_ARCH_TAG}-x86_64.sh"
    - "wget https://github.com/conda-forge/conda-forge-anvil/raw/master/constructions/${CONSTRUCTION} -O ${HOME}/cache/${CONSTRUCTION} || :"
    - bash ${HOME}/cache/${CONSTRUCTION} -b -p ${CONDA_INSTALL_LOCN} && export PATH=${CONDA_INSTALL_LOCN}/bin:$PATH

    # Re-use the packages in the cache, and download any new ones into that location.
    - rm -rf ${CONDA_INSTALL_LOCN}/pkgs && ln -s ${HOME}/cache/pkgs ${CONDA_INSTALL_LOCN}/pkgs

script:
    - conda list


# We store the files that are downloaded from continuum.io, but not the environments that are created.
cache:
    directories:
      - $HOME/cache
before_cache:
  # Remove all untarred directories.
  - find $CONDA_INSTALL_LOCN/pkgs/ -mindepth 1 -maxdepth 1 -type d -exec rm -r {} \;
