# The language in this case has no bearing - we are going to be making use of conda for a
# python distribution for the scientific python stack.
language: generic

sudo: false

env:
    global:
       - CONDA_INSTALL_LOCN="${HOME}/conda"
#       - CONSTRUCTION="anvil-0.1-MacOSX-x86_64.sh"  #LAB

#-rwxr-xr-x  1 loriab  staff  25401955 Jul 16 18:17 anvil-0.1.1-py27-MacOSX-x86_64.sh
#-rwxr-xr-x  1 loriab  staff  35652113 Jul 16 18:18 anvil-0.1.1-py34-MacOSX-x86_64.sh
#-rwxr-xr-x  1 loriab  staff  38468113 Jul 16 18:18 anvil-0.1.1-py35-MacOSX-x86_64.sh

    matrix:
        - PYTHON_STRING=py27  CONSTRUCTION="anvil-0.1.1-${PYTHON_STRING}-MacOSX-x86_64.sh"
        - PYTHON_STRING=py34  CONSTRUCTION="anvil-0.1.1-${PYTHON_STRING}-MacOSX-x86_64.sh"
        - PYTHON_STRING=py35  CONSTRUCTION="anvil-0.1.1-${PYTHON_STRING}-MacOSX-x86_64.sh"
#LAB        - PYTHON=2.7
#LAB        - PYTHON=3.5

matrix:
  include:
    - os: osx
    
install:
    - mkdir -p ${HOME}/cache/pkgs
#LAB    - "[ ! -f ${HOME}/cache/miniconda.sh ] && wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ${HOME}/cache/miniconda.sh || :"
    - "wget https://github.com/loriab/anvil/raw/master/${CONSTRUCTION} -O ${HOME}/cache/${CONSTRUCTION} || :"
    - bash ${HOME}/cache/${CONSTRUCTION} -b -p ${CONDA_INSTALL_LOCN} && export PATH=${CONDA_INSTALL_LOCN}/bin:$PATH

    # Re-use the packages in the cache, and download any new ones into that location.
    - rm -rf ${CONDA_INSTALL_LOCN}/pkgs && ln -s ${HOME}/cache/pkgs ${CONDA_INSTALL_LOCN}/pkgs

    # Now do the things we need to do to install it.
#LAB    - conda install --file requirements.txt nose mock python=${PYTHON} --yes --quiet -c conda-forge
#LAB    - python setup.py install

script:
#LAB    - nosetests conda_smithy
    - conda list


# We store the files that are downloaded from continuum.io, but not the environments that are created.
cache:
    directories:
      - $HOME/cache
before_cache:
  # Remove all untarred directories.
  - find $CONDA_INSTALL_LOCN/pkgs/ -mindepth 1 -maxdepth 1 -type d -exec rm -r {} \;
